[package]
name = "sudo-gcp"
version = "0.1.0"
edition = "2021"

readme = "README.md"
license = "Apache-2.0"
description = "reserved for future development"

[dependencies]
clap = { version = "4.3.4", features = ["derive"] }
reqwest = { version = "0.11.18", features = ["json"] }
